Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2019-11, with the labels that each got.

#873 Fix typo Kindgom -> Kingdom
  src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Labels: bug

#901 EES-642 Mapping InternalReleaseNote and ReleaseStatus fields
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
Labels: bug

#902 Test/ees 647 fix data api tests
  tests/newman/tests/DfE Data API - Test data.postman_collection.json
  tests/newman/tests/data-api.json
Labels: testing

#908 EES-633 Fix migration SQL files not being found
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131048_InitialCreate.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131048_InitialCreate.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131247_IntialCreate_Custom.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131247_IntialCreate_Custom.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190830082721_AddCsvRowFieldToObservation.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190830082721_AddCsvRowFieldToObservation.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191008162516_UpdateFilteredObservationsStoredProc.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191008162516_UpdateFilteredObservationsStoredProc.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191101153547_Ees263UpdateFilteredObservationsStoredProc.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191101153547_Ees263UpdateFilteredObservationsStoredProc.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/StatisticsDbContextModelSnapshot.cs
Labels: bug

#909 Bugfix/ees 633
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
Labels: enhancement

#904 EES-226 Distinct Observational Unit labels
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/LabelValue.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractTableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderResultSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/ObservationalUnitGeoJsonMeta.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/ObservationalUnitMetaViewModel.cs
Labels: bug

#930 New FootnoteViewModel for Admin
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteFilterGroupViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteFilterViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteIndicatorGroupViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteSubjectViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
  tests/newman/tests/admin-api.json
  useful-scripts/sql/FootnoteData.sql
Labels: enhancement

#942 EES-350 Trim leading and trailing whitespace.
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/CsvUtil.cs
Labels: bug

#955 EES-745 Removing the IdWrapper query type
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/IdWrapper.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/StatisticsDbContextModelSnapshot.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
Labels: bug

#967 EES-731 Returning filter item and indicator id's as strings.
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteFilterGroupViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteIndicatorGroupViewModel.cs
Labels: enhancement, front end

#972 EES-146 Download data files
  src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypePublicationService.ts
  src/explore-education-statistics-common/src/services/publicationService.ts
Labels: front end

#969 EES-668 Adding list of Download files to ManageContentPageViewModel
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IFileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ManageContentPageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ManageContent/ManageContentPageViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Seed/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
Labels: enhancement

#982 EES-767 Ignoring types from other assemblies which can't be loaded
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/DataMappingProfiles.cs
Labels: bug

#977 EES-146 Download files link needs to use the Admin edit release service rather than point at the Data API
  src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
  src/explore-education-statistics-admin/src/services/release/edit-release/data/service.ts
Labels: enhancement, front end

#691 EES-259 Preparing for indicator enrolments_pa10_exact_percent to be r…
  useful-scripts/sql/FootnoteData.sql
Labels: data refresh

#981 EES-664 Adding API to create Release Notes
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ManageContent/CreateReleaseNoteRequest.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ManageContent/ReleaseNoteController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/ManageContent/IReleaseNoteService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ReleaseNoteService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
  tests/newman/tests/admin-api.json
Labels: enhancement
