Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2019-09, with the labels that each got.

#660 DFE-1392 Changing the query object in Fastrack to include the Publica…
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FastTrackService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/FastTrackViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/PermalinkViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/TableBuilderQueryViewModel.cs
  src/explore-education-statistics-common/src/modules/full-table/services/permalinkService.ts
  src/explore-education-statistics-common/src/modules/full-table/services/tableBuilderService.ts
  src/explore-education-statistics-common/src/modules/full-table/types/fullTable.ts
  src/explore-education-statistics-common/src/modules/full-table/utils/mapPermalinks.ts
  src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
  src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/DownloadCsvButton.test.tsx
Labels: enhancement

#671 Bugfix/dfe 1317
  armTemplates/ees-service/template.json
  src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/NotifySubscribersMessage.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/NotificationsService.cs
  src/GovUk.Education.ExploreEducationStatistics.Notifier.Model/GovUk.Education.ExploreEducationStatistics.Notifier.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Notifier.Model/PublicationNotificationMessage.cs
  src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
  src/GovUk.Education.ExploreEducationStatistics.Notifier/PublicationNotification.cs
  src/GovUk.Education.ExploreEducationStatistics.Notifier/PublicationNotifier.cs
  src/GovUk.Education.ExploreEducationStatistics.sln
Labels: bug

#668 DFE-1309 Other releases don't need to include the release
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/ReleaseService.cs
Labels: bug

#679 Bug/ees 31 ie11 maps
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/UserDetailsPermissionsViewModel.cs
  src/explore-education-statistics-common/src/polyfill.js
Labels: bug

#622 INFRA: Re-enables the processing of files once uploaded
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs
Labels: enhancement

#687 EES-56, EES-203 Testing FastTrack and Permalinks
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controller/FastTrackControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controller/PermalinkControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/FastTrackController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/PermalinkController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FileStorageService.cs
  tests/newman/tests/data-api.json
Labels: bug, enhancement

#692 EES-105 Add missing mappings
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/ProcessorMappingProfiles.cs
Labels: bug

#695 Correcting logger
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublishingService.cs
Labels: bug

#699 EES-105 Adding missing mapping for Release.ReleaseDate
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/ProcessorMappingProfiles.cs
Labels: bug

#723 EES-73 Adding PUT Update DataBlock to DataBlocksController
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/DataBlocksControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/DataBlocksController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/UpdateDataBlockViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IDataBlockService.cs
Labels: enhancement
