Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2019-10, with the labels that each got.

#786 Fixing permalinks regression issue due to changes in Filter serialisa…
  src/explore-education-statistics-admin/src/services/release/edit-release/datablocks/service.ts
  src/explore-education-statistics-common/src/modules/full-table/types/filters.ts
Labels: bug

#788 EES-313 Improving performance getting Subject meta by retrieving data…
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderMetaController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FilterItemService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FilterService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFilterItemService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFilterService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/ILocationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/LocationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractTableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ITableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ITimePeriodService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/TimePeriodService.cs
Labels: enhancement

#790 Feature/ees 316
  tests/newman/tests/data-api.json
Labels: testing

#795 Test: Added local backup and restore scripts for the UI tests
  .gitignore
  src/Dockerfile-Content-Api
  tests/robot-tests/Pipfile
  tests/robot-tests/Pipfile.lock
  tests/robot-tests/README.md
  tests/robot-tests/backup-local.py
  tests/robot-tests/restore-local.py
Labels: testing

#804 Feature/ees 315
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/PublicationControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/TableBuilderControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ThemeControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/DataController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/TableBuilderController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/TableBuilderMetaController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderMetaControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/DataController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/MetaController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderMetaController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Query/ObservationQueryContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Query/SubjectMetaQueryContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Query/TimePeriodQuery.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/AbstractRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/BoundaryLevelService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/DataServiceMemoryCache.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/GeoJsonService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IGeoJsonService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SubjectService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/DataService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
Labels: enhancement

#813 EES-315 Updating Data API Postman Tests. Removing one LAD test with n…
  tests/newman/tests/data-api.json
Labels: testing

#814 EES-418 Page Search inputLabels
  src/explore-education-statistics-common/src/components/PageSearchForm.tsx
  src/explore-education-statistics-common/src/components/__tests__/PageSearchForm.test.tsx
  src/explore-education-statistics-frontend/src/modules/download/DownloadIndexPage.tsx
  src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
  src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
  src/explore-education-statistics-frontend/src/modules/glossary/GlossaryIndexPage.tsx
  src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyIndexPage.tsx
  src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
Labels: enhancement

#819 EES-434 Correcting methodology link
  src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
Labels: bug, front end

#818 EES 289 fixes
  tests/newman/files/small-files/LEP.csv
  tests/newman/files/small-files/MCA.csv
  tests/newman/files/small-files/all_geographies.csv
  tests/newman/files/small-files/all_geographies_messy.csv
Labels: bug

#817 Bugfix/ees 237
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Models/GeographicLevels.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/GeographicLevel.cs
  src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
Labels: bug

#826 EES-511 Zip all files when they are copied to the public release directory
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
  src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Model/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Model/Services/Interfaces/IFileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Extensions/FileExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Models/SubjectData.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/BatchService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/Interfaces/IFileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Utils/BlobUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Seed/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentCacheGenerationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/host.json
Labels: enhancement

#827 EES-512 - Display the zip of all files for download
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
Labels: enhancement

#841 EES-311 Admin Manage Footnotes API
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/DataBlocksController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/CreateFootnoteViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/UpdateFootnoteViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Footnote.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/AbstractRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFootnoteService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IRepository.cs
Labels: enhancement

#844 EES-311 Admin API tests for footnotes
  tests/newman/tests/admin-api.json
Labels: enhancement, testing

#842 EES-494 - adding overrides for the print media styles on the tabs as …
  src/explore-education-statistics-common/src/components/Accordion.module.scss
  src/explore-education-statistics-common/src/components/TabsSection.module.scss
  src/explore-education-statistics-common/src/modules/find-statistics/components/SummaryRenderer.module.scss
  src/explore-education-statistics-common/src/styles/_print.scss
Labels: front end
