Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2019-08, with the labels that each got.

#450 DFE-950 cookies banner
  src/explore-education-statistics-frontend/package-lock.json
  src/explore-education-statistics-frontend/package.json
  src/explore-education-statistics-frontend/server.js
  src/explore-education-statistics-frontend/src/components/CookieBanner.module.scss
  src/explore-education-statistics-frontend/src/components/CookieBanner.tsx
  src/explore-education-statistics-frontend/src/hooks/useCookies.ts
  src/explore-education-statistics-frontend/src/modules/cookies/CookiesIndexPage.module.scss
  src/explore-education-statistics-frontend/src/modules/cookies/CookiesIndexPage.tsx
  src/explore-education-statistics-frontend/src/pages/_app.tsx
  src/explore-education-statistics-frontend/src/pages/cookies.tsx
  src/explore-education-statistics-frontend/src/pages/cookies/details.tsx
  src/explore-education-statistics-frontend/src/pages/cookies/index.tsx
  src/explore-education-statistics-frontend/src/services/googleAnalyticsService.ts
Labels: enhancement

#509 Feature/dfe 1013
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartAxisConfiguration.tsx
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartBuilder.tsx
  src/explore-education-statistics-admin/src/pages/prototypes/PrototypeChartTest.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/HorizontalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/LineChartBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/VerticalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/HorizontalBarBlock.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/LineChartBlock.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/VerticalBarBlock.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__data__/testBlockData.ts
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__data__/testResponseData_23_26_28__1_2_LAD.json
  src/explore-education-statistics-common/src/services/publicationService.ts
Labels: enhancement

#533 DFE-1015 - Adding title to charts and re-arranging the chart configur…
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartBuilder.tsx
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartConfiguration.tsx
  src/explore-education-statistics-admin/src/modules/chart-builder/graph-builder.module.scss
  src/explore-education-statistics-common/src/modules/find-statistics/components/ChartRenderer.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/MapBlock.tsx
Labels: enhancement

#528 Feature/dfe 1009
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartAxisConfiguration.tsx
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartBuilder.tsx
  src/explore-education-statistics-admin/src/pages/prototypes/PrototypeChartTest.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/HorizontalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/LineChartBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/VerticalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/HorizontalBarBlock.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/LineChartBlock.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/VerticalBarBlock.test.tsx
  src/explore-education-statistics-common/src/services/publicationService.ts
Labels: enhancement

#532 Bug/20190805 charts assorted minor bugs
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartAxisConfiguration.tsx
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartBuilder.tsx
  src/explore-education-statistics-admin/src/modules/chart-builder/graph-builder.module.scss
  src/explore-education-statistics-admin/src/pages/prototypes/PrototypeChartTest.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/HorizontalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/LineChartBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/VerticalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/HorizontalBarBlock.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/VerticalBarBlock.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__data__/testBlockData.ts
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__snapshots__/HorizontalBarBlock.test.tsx.snap
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__snapshots__/LineChartBlock.test.tsx.snap
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__snapshots__/VerticalBarBlock.test.tsx.snap
  src/explore-education-statistics-common/src/services/publicationService.ts
Labels: bug

#541 DFE-1254 Adding support for the Pound (£) unit.
  src/GovUk.Education.ExploreEducationStatistics.Common/Converters/EnumToEnumValueJsonConverter.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Services/EnumUtil.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Converters/EnumToEnumValueConverter.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Unit.cs
Labels: enhancement

#540 DFE-1137 Filter out null measures.
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/ResultBuilder.cs
Labels: bug

#573 Feature/dfe 1277 permalink backend
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controller/PermalinkControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controller/TableBuilderControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/DownloadController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/PermalinkController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Extensions/TimePeriodExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Migrations/ApplicationDbContextModelSnapshot.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/LabelValue.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/Permalink.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/PermalinkEntity.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/Query/PermalinkQueryContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/Query/TableBuilderConfiguration.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/Query/TableBuilderTableHeadersConfig.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Program.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/AbstractDataService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/DataService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IDataService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IFileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IObservationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IPermalinkService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/ISubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/ITableBuilderResultSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/ITimePeriodService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/ObservationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/ResultBuilder.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/SubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TableBuilderDataService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TableBuilderResultSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TimePeriodService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TimePeriodUtil.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/LabelValueViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/ObservationalUnitGeoJsonMeta.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/ObservationalUnitMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/SubjectMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/TableBuilder/TableBuilderFilterItemMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/TableBuilder/TableBuilderObservationalUnitsMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/TableBuilder/TableBuilderResultSubjectMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/TimePeriodMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/PermalinkViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/ResultViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/TableBuilderResultViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FilterItemService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/IndicatorService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFilterItemService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFootnoteService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IIndicatorService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/ILocationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/LocationService.cs
Labels: enhancement

#583 DFE-1300 Adding BoundaryLevel options to metaData response
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/SubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/SubjectMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/AbstractRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/BoundaryLevelService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IBoundaryLevelService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IRepository.cs
Labels: enhancement

#585 DFE-1329 Group FilterItems in FullTable™ response for rendering FullT…
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/AbstractTableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TableBuilderResultSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TableBuilderSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/TableBuilder/TableBuilderResultFilterItemMetaViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/TableBuilder/TableBuilderResultSubjectMetaViewModel.cs
Labels: enhancement

#604 Feature/dfe 1350
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controller/TableBuilderControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/ResultViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/ResultWithMetaViewModel.cs
  tests/newman/tests/data-api.json
Labels: enhancement

#616 DFE-1353 Comparing FilterGroup and Filters by their Id when using Gro…
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/AbstractTableBuilderSubjectMetaService.cs
Labels: bug

#634 DFE-980 Adding missing BoundaryLevel mapping.
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Mappings/MappingProfiles.cs
Labels: bug

#633 DFE-980 Adding Statistics database context to the Admin application. …
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/TableBuilderMetaController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/DataMappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Migrations/20190819131048_InitialCreate.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Migrations/20190819131247_IntialCreate_Custom.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Migrations/StatisticsDbContextModelSnapshot.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterFilterService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterLocationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterSchoolService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/AbstractRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/BoundaryLevelService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FilterGroupService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FilterItemService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FilterService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/GeoJsonService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/IndicatorGroupService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/IndicatorService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/LocationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/ReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SchoolService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SubjectService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Processor.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileImportService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ReleaseProcessorService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Seed/Program.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
Labels: bug, enhancement

#643 Bug/dfe 1062
  src/explore-education-statistics-admin/src/pages/prototypes/PrototypeChartTest.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/ChartRenderer.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/MapBlock.tsx
Labels: bug

#651 Bug/dfe 1385 charts not sorting correctly
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/ChartFunctions.test.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__data__/chartFunctionsData.ts
Labels: bug
