Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2020-02, with the labels that each got.

#1226 Update dependencies
  .eslintrc.json
  package-lock.json
  package.json
  src/explore-education-statistics-admin/package-lock.json
  src/explore-education-statistics-admin/package.json
  src/explore-education-statistics-admin/src/components/ImporterStatus.tsx
  src/explore-education-statistics-admin/src/components/ReleaseServiceStatus.tsx
  src/explore-education-statistics-admin/src/modules/chart-builder/ChartBuilder.tsx
  src/explore-education-statistics-admin/src/modules/find-statistics/components/ReleaseContentAccordion.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
  src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypeEditableContent.tsx
  src/explore-education-statistics-admin/src/pages/release/create-release/CreateReleasePage.tsx
  src/explore-education-statistics-admin/src/pages/release/edit-release/data/ReleaseFootnotesSection.tsx
  src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/DataBlockDetailsForm.tsx
  src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/ReleaseManageDataBlocksPage.tsx
  src/explore-education-statistics-admin/src/pages/release/util/releaseSummaryUtil.ts
  src/explore-education-statistics-admin/src/services/applicationInsightsService.ts
  src/explore-education-statistics-common/.babelrc
  src/explore-education-statistics-common/package-lock.json
  src/explore-education-statistics-common/package.json
  src/explore-education-statistics-common/src/components/AriaLiveMessage.tsx
  src/explore-education-statistics-common/src/components/PageSearchForm.tsx
  src/explore-education-statistics-common/src/components/Tabs.tsx
  src/explore-education-statistics-common/src/components/form/index.ts
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx
  src/explore-education-statistics-common/src/modules/find-statistics/components/charts/MapBlock.tsx
  src/explore-education-statistics-common/src/modules/full-table/utils/tableHeaders.ts
  src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
  src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.tsx
  src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx
  src/explore-education-statistics-common/src/modules/table-tool/components/Wizard.tsx
  src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FixedMultiHeaderDataTable.test.tsx
  src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/MultiHeaderTable.test.tsx
  src/explore-education-statistics-common/src/polyfill.js
  src/explore-education-statistics-frontend/babel.config.js
  src/explore-education-statistics-frontend/package-lock.json
  src/explore-education-statistics-frontend/package.json
  src/explore-education-statistics-frontend/src/modules/download/DownloadIndexPage.tsx
  src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
  src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyIndexPage.tsx
  src/explore-education-statistics-frontend/src/services/googleAnalyticsService.ts
Labels: dependencies

#1273 EES-1261 Types were wrong
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/PublicationController.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/ContactViewModel.cs
  src/explore-education-statistics-common/src/services/publicationService.ts
  src/explore-education-statistics-frontend/src/modules/subscriptions/SubscriptionPage.tsx
Labels: enhancement

#1285 EES-1227 Release view model combines cached Publication and Release view models
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ManageContent/ManageContentPageViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DownloadControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/MethodologyControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ReleaseController.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Models/PublicationViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Models/ReleaseViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/CachedPublicationViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/CachedReleaseViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/ExternalMethodologyViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/ReleaseTitleViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/ReleaseViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublicationServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublicationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublicationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
  src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
  src/explore-education-statistics-admin/src/pages/prototypes/components/EditablePublicationPage.tsx
  src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypePublicationService.ts
  src/explore-education-statistics-common/src/services/publicationService.ts
  src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
  src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/content.api.response.national.stats.json
  src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/content.api.response.official.stats.json
Labels: bug, enhancement

#1290 EES-1279 Work out the next scheduled publish date if the release has …
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
Labels: bug

#1300 EES-1226 Fix Release links
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Models/ReleaseViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublicationServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublicationService.cs
  src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
  src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/content.api.response.national.stats.json
  src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/content.api.response.official.stats.json
Labels: bug

#1309 EES-1277 Fixing content section and section content block ordering.
  src/GovUk.Education.ExploreEducationStatistics.Publisher/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
Labels: bug

#1314 EES-1224 Appending messages if a stage fails
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ReleaseStatus.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/DataFactoryPipelineStatusFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/GenerateReleaseContentFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseDataFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseFilesFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseStatusService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs
Labels: enhancement

#1312 EES-1277 Unit tests for ordering of sections and content blocks withi…
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
Labels: enhancement

#1389 EES-1426 Altering Public Storage to be a property rather than a conne…
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.Development.json
Labels: bug

#1390 EES-1427 enabling the PublishReleaseDataFunction in Test and Prod
  infrastructure/parameters/dev.parameters.json
  infrastructure/templates/template.json
Labels: enhancement
