Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2020-07, with the labels that each got.

#1789 EES-980 Move release publishing fields to release status page
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UpdateReleaseRequest.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UpdateReleaseStatusRequest.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/CreateReleaseViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/MyReleaseViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/ReleaseViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/DateTimeFormatValidator.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
  src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleasesTab.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/NonScheduledReleaseSummary.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ReleaseSummary.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ReleasesByStatusTab.tsx
  src/explore-education-statistics-admin/src/pages/release/ReleaseCreatePage.tsx
  src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx
  src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryEditPage.tsx
  src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryPage.tsx
  src/explore-education-statistics-admin/src/pages/release/components/ReleaseSummaryForm.tsx
  src/explore-education-statistics-admin/src/pages/release/content/components/BasicReleaseSummary.tsx
  src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
  src/explore-education-statistics-admin/src/services/dashboardService.ts
  src/explore-education-statistics-admin/src/services/releaseService.ts
  src/explore-education-statistics-common/src/components/SummaryList.tsx
  src/explore-education-statistics-common/src/components/form/FormFieldDateInput.tsx
  src/explore-education-statistics-common/src/components/form/FormRadioGroup.tsx
  src/explore-education-statistics-common/src/components/form/__tests__/FormFieldDateInput.test.tsx
  src/explore-education-statistics-common/src/services/publicationService.ts
  src/explore-education-statistics-common/src/utils/date/__tests__/partialDate.test.ts
  src/explore-education-statistics-common/src/utils/date/partialDate.ts
  src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
  tests/newman/tests/admin-api-dev.json
  tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
  tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
  tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
  tests/robot-tests/tests/admin/bau/delete_subject.robot
  tests/robot-tests/tests/admin/bau/manage_content.robot
  tests/robot-tests/tests/admin_and_public/bau/publish_release.robot
  tests/robot-tests/tests/general_public/miscellaneous.robot
  tests/robot-tests/tests/general_public/permalink_prod_1.robot
  tests/robot-tests/tests/general_public/permalink_prod_2.robot
  tests/robot-tests/tests/general_public/permalink_prod_3.robot
  tests/robot-tests/tests/libs/admin-common.robot
  tests/robot-tests/tests/libs/common.robot
Labels: do not merge

#1794 EES-1094 Updating infra to use dev branch on Dev and Test envs
  azure-pipelines.dfe.yml
  infrastructure/infrastructure-pipeline.yml
  infrastructure/parameters/dev.parameters.json
  infrastructure/parameters/test.parameters.json
  infrastructure/templates/template.json
Labels: do not merge

#1823 EES-1151
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/ValidateReleaseFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseStatusService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ValidationService.cs
Labels: bug

#1827 API Test fixes
  tests/newman/tests/admin-api-dev.json
  tests/newman/tests/admin-api.json
  tests/newman/tests/data-api.json
Labels: testing

#1762 EES-1009 Upgrade to .NET Core 3.1
  azure-pipelines.dfe.yml
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/GovUk.Education.ExploreEducationStatistics.Admin.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
  src/GovUk.Education.ExploreEducationStatistics.Admin/Program.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/GovUk.Education.ExploreEducationStatistics.Common.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Program.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Content.Model/GovUk.Education.ExploreEducationStatistics.Content.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Program.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Importer/GovUk.Education.ExploreEducationStatistics.Data.Importer.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Model/GovUk.Education.ExploreEducationStatistics.Data.Processor.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileImportService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Seed/GovUk.Education.ExploreEducationStatistics.Data.Seed.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
  src/GovUk.Education.ExploreEducationStatistics.Notifier.Model/GovUk.Education.ExploreEducationStatistics.Notifier.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/GovUk.Education.ExploreEducationStatistics.Publisher.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/GovUk.Education.ExploreEducationStatistics.Publisher.Tests.csproj
  src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj
Labels: dependencies

#1876 EES-1205 Temporarily downgrading Notifier dependency Microsoft.NET.Sdk.Functions to 3.0.3
  src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
  src/GovUk.Education.ExploreEducationStatistics.Notifier/PublicationNotifier.cs
Labels: bug
