Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2020-05, with the labels that each got.

#1628 EES-678 Add external methodology
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Labels: bug

#1631 EES-802 Fix 'open datareader' error migrating datablocks
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockMigrationService.cs
Labels: bug

#1633 EES-812 Only query subject meta by subject Id and cache it
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockMigrationService.cs
Labels: bug

#1634 EES-812 Skip newer datablocks and allow for 'term' time identifiers
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockMigrationService.cs
Labels: bug

#1642 Bugfix/ees 816
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DateTimeExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs
Labels: bug

#1647 EES-818 Getting Publication and Release Titles for PreRelease page outside window
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/PreReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/PreReleaseController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPreReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PreReleaseSummaryViewModel.cs
  src/explore-education-statistics-admin/src/pages/release/prerelease/PreReleasePage.tsx
  src/explore-education-statistics-admin/src/services/pre-release/preReleaseService.ts
Labels: bug

#1655 EES-882 Attempt to use AppendCloudBlob in Azure. Don't delay Startup
  src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IFileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkMigrationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
Labels: enhancement

#1659 EES-638 Adding contact team email to display on PreRelease page
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/PreReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PreReleaseSummaryViewModel.cs
  src/explore-education-statistics-admin/src/pages/release/prerelease/PreReleasePage.tsx
  src/explore-education-statistics-admin/src/services/pre-release/preReleaseService.ts
Labels: enhancement

#1667 EES-855 Use DateTimeKind.Unspecified before converting time.
  src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DateTimeExtensions.cs
Labels: bug

#1669 EES-857 Specify database conversion with DateTimeKind UTC on Release.PublishScheduled
  src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs
Labels: bug

#1670 EES-863
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/EES17DataBlockMappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockMigrationService.cs
Labels: bug

#1671 EES-778
  src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IFileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkMigrationService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
Labels: bug

#1675 EES-818 Adding check to see if user has permission to view a specific PreRelease Summary or Status Window.
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/PreReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificPreReleaseSummaryAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseSummaryServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseSummaryServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/PreReleaseController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewSpecificPreReleaseSummaryRequirement.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityPolicies.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/StartupSecurityConfiguration.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPreReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPreReleaseSummaryService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensionMethods.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseSummaryService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
  src/explore-education-statistics-admin/src/pages/errors/ForbiddenPage.tsx
  src/explore-education-statistics-admin/src/pages/release/prerelease/PreReleasePage.tsx
  src/explore-education-statistics-common/src/hooks/useAsyncCallback.ts
Labels: bug

#1684 EES-348 Handle invalid Guids as 404's when getting FastTrack and Permalinks
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/FastTrackControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/PermalinkControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/FastTrackController.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/PermalinkController.cs
Labels: bug

#1680 EES-763 Add required title/alt text fields for charts
  src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/IContentBlockChart.cs
  src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
  src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilder.tsx
  src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartConfiguration.tsx
  src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/DataBlockDetailsForm.tsx
  src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/reducers/__tests__/chartBuilderReducer.test.ts
  src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/reducers/chartBuilderReducer.ts
  src/explore-education-statistics-admin/src/pages/release/edit-release/status/ReleaseStatusPage.tsx
  src/explore-education-statistics-common/src/components/form/FormBaseInput.tsx
  src/explore-education-statistics-common/src/components/form/FormFieldset.tsx
  src/explore-education-statistics-common/src/components/form/FormFileInput.tsx
  src/explore-education-statistics-common/src/components/form/FormTextArea.tsx
  src/explore-education-statistics-common/src/components/form/FormTextSearchInput.tsx
  src/explore-education-statistics-common/src/components/form/__tests__/FormBaseInput.test.tsx
  src/explore-education-statistics-common/src/components/form/__tests__/FormTextArea.test.tsx
  src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormFieldset.test.tsx.snap
  src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormTextArea.test.tsx.snap
  src/explore-education-statistics-common/src/components/form/util/createDescribedBy.ts
  src/explore-education-statistics-common/src/modules/charts/components/ChartRenderer.tsx
  src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/charts/components/InfographicBlock.tsx
  src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx
  src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/charts/types/chart.ts
  src/explore-education-statistics-common/src/types/recharts.d.ts
Labels: do not merge

#1698 EES-890 Fix converter on Status of UpdateMethodologyRequest.
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/UpdateMethodologyRequest.cs
Labels: bug

#1699 EES-890 Fix methodology unique slug validation failing when updating methodology
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ValidationTestUtil.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
Labels: bug

#1697 EES-910 Date and time string parameters for Prerelease email body
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificReleaseAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/PreReleaseWindow.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Models/PreReleaseWindowStatus.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewSpecificReleaseAuthorizationHandlers.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPreReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseContactsService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DateTimeExtensions.cs
  src/explore-education-statistics-admin/src/services/permissions/permissionService.ts
Labels: bug

#1705 EES-927 Fix validation error creating methodology.
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/CreateMethodologyRequest.cs
Labels: bug

#1709 EES-786 Corrections to published date of Releases and Methogologies.
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/CronScheduleUtilTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/GenerateReleaseContentFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentImmediateFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Models/PublishContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IContentService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
  tests/newman/tests/admin-api-dev.json
Labels: bug

#1715 EES-946 Using the Release page file path
  src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Labels: bug
