Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2020-06, with the labels that each got.

#1718 EES-945 Don't zip infographics files in the charts directory
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Models/CopyReleaseFilesCommand.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IFileStorageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ZipFileUtil.cs
Labels: bug

#1721 EES-856 Cleanup content block API tests
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ManageContent/ContentController.cs
  tests/newman/tests/admin-api-dev.json
Labels: testing

#1725 EES-738 Copy DecimalPlaces
  infrastructure/templates/datafactory/components/template.json
Labels: bug

#1734 EES-975 Fixing Admin API Tests
  tests/newman/tests/admin-api.json
Labels: testing

#1743 EES-975 Fix various failing Admin API (Dev) Tests
  tests/newman/tests/admin-api-dev.json
Labels: testing

#1744 EES-856 Prevent Content endpoint being used to create content block of type 'DataBlock'
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ContentService.cs
  tests/newman/tests/admin-api-dev.json
Labels: bug, testing

#1751 EES-887 PreRelease fixes
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
  src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
Labels: bug

#1757 EES-381: Admin sign in link style
  src/explore-education-statistics-admin/src/pages/errors/ForbiddenPage.tsx
  src/explore-education-statistics-admin/src/pages/sign-in/SignedOutPage.tsx
Labels: bug

#1759 EES-1015 Adding support for weekly data and releases
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/TimePeriodLabelFormatterTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifierCategory.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/Extensions/TimeIdentifierExtensionsTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimeIdentifierUtilTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimePeriodUtilTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/Extensions/TimeIdentifierExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/TimeIdentifierUtil.cs
  src/explore-education-statistics-admin/src/pages/release/summary/ReleaseSummaryForm.tsx
Labels: enhancement

#1761 EES-1019 Add sorting to filter groups and filter items in Subject metadata requests
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractSubjectMetaService.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/LabelRelationalComparer.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
Labels: enhancement

#1763 Revert "EES-986 Delete observation filter items when delete subject."
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SubjectService.cs
Labels: bug

#1772 EES-1031 Use query param for the subject title
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/PublicationController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs
  src/explore-education-statistics-admin/src/services/releaseDataFileService.ts
Labels: bug

#1771 EES-990 Find the correct ReleaseFileReference when importing files
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ReleaseProcessorService.cs
Labels: bug

#1756 Order contacts alphabetically
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ContactService.cs
Labels: bug
