Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2021-06, with the labels that each got.

#2563 EES-2355 Allow Publication Owner to change Release statuses between Draft and Higher Level Review
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ReleaseStatusAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ReleaseStatusAuthorizationHandlers.cs
Labels: bug

#2565 EES-1263 Change the build pipeline to build PR's which target the EES-1263-SOW4 branch
  azure-pipelines.dfe.yml
Labels: SOW4

#2566 Ees 2203 make methodology amendment auth handler
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MakeAmendmentOfSpecificMethodologyAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificMethodologyAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/Utils/AuthorizationHandlersTestUtil.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ImportStatusBauServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ManageContent/ContentServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyAmendmentServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyContentServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseChecklistServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseImageServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseStatusServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/TopicServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MakeAmendmentOfSpecificMethodologyAuthorizationHandlers.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/UpdateSpecificMethodologyAuthorizationHandlers.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityClaimTypes.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityPolicies.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/StartupSecurityConfiguration.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyAmendmentService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyAmendmentService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyContentService.cs
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/AssertExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/EitherTest.cs
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/MockUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/PolicyCheckBuilder.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Services/CollectionUtils.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/MethodologyTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Model/Methodology.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Security/DefaultAuthenticationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServicePermissionTests.cs
Labels: SOW4

#2561 EES-2350 initial FE work for new create methodology (WIP)
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ManagePublicationsAndReleasesTab.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologyExternalLinkForm.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologyExternalLinkForm.test.tsx
  src/explore-education-statistics-admin/src/pages/methodology/MethodologiesPage.tsx
  src/explore-education-statistics-admin/src/pages/methodology/MethodologyCreatePage.tsx
  src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/MethodologyPage.tsx
  src/explore-education-statistics-admin/src/pages/publication/PublicationEditPage.tsx
  src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx
  src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationForm.test.tsx
  src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusChecklist.tsx
  src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusChecklist.test.tsx
  src/explore-education-statistics-admin/src/routes/methodologyRoutes.ts
  src/explore-education-statistics-admin/src/routes/routes.ts
Labels: SOW4

#2570 EES-2368 Stop Publication appearing twice in the Dashboard if granted via the Publication Owner role as well as a Release role
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationRepositoryTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationRepository.cs
Labels: SOW3

#2579 Ees 2220 support for new create methodology process
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ConfigurationControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Methodologies/MethodologyControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/PreReleaseControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/CreateMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MakeAmendmentOfSpecificMethodologyAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ManageContent/ContentServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyRepositoryTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseChecklistServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseStatusServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ConfigurationController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/MethodologyController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/CreateMethodologyForSpecificPublicationAuthorizationHandlers.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityPolicies.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/StartupSecurityConfiguration.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ActionResultTestExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EitherTestExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Security/ContentSecurityPolicies.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Security/Extensions/UserServiceExtensions.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
  src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseServicePermissionTests.cs
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
  src/explore-education-statistics-admin/src/pages/methodology/MethodologyCreatePage.tsx
  src/explore-education-statistics-admin/src/routes/routes.ts
  src/explore-education-statistics-admin/src/services/methodologyService.ts
Labels: SOW4

#2583 EES-2199 amend methodology and related buttons
  src/explore-education-statistics-admin/package.json
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
  src/explore-education-statistics-admin/src/services/methodologyService.ts
  src/explore-education-statistics-admin/src/services/publicationService.ts
  src/explore-education-statistics-admin/test/createMemoryHistoryWithMockedPush.ts
  src/explore-education-statistics-admin/tsconfig.json
Labels: SOW4

#2604 Ees 2222 UI tests for sow4 create methodology flow
  Pipfile
  Pipfile.lock
  src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
  src/explore-education-statistics-admin/src/pages/methodology/MethodologiesPage.tsx
  src/explore-education-statistics-admin/src/routes/routes.ts
  tests/robot-tests/listeners/KeywordListener.py
  tests/robot-tests/run_tests.py
  tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
  tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
  tests/robot-tests/tests/libs/admin-common.robot
  tests/robot-tests/tests/libs/common.robot
Labels: SOW4

#2607 EES-2395 Show links to Methodologies from Admin Manage Content page
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ManageContent/ManageContentPageServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ManageContentPageService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs
  src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
  src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHelpAndSupportSection.tsx
Labels: SOW4

#2603 EES-1890 Change Content DB to use vCores
  infrastructure/parameters/prod.parameters.json
  infrastructure/templates/template.json
Labels: do not merge

#2615 EES-2378 Reinstate support for the public View All Methodologies page and support multiple Methodologies
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ThemeController.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/Interfaces/IMethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/MethodologyTreeNode.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/PublicationMethodologiesTreeNode.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
  src/explore-education-statistics-common/src/services/themeService.ts
  src/explore-education-statistics-frontend/src/modules/methodologies/components/MethodologyList.tsx
Labels: SOW4

#2624 EES-2458 Remove unused BAU methodologies page
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServicePermissionTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/MethodologyController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyPublicationsViewModel.cs
  src/explore-education-statistics-admin/src/components/PageFooter.tsx
  src/explore-education-statistics-admin/src/components/PageHeader.tsx
  src/explore-education-statistics-admin/src/pages/bau/BauDashboardPage.tsx
  src/explore-education-statistics-admin/src/pages/bau/BauMethodologyPage.tsx
  src/explore-education-statistics-admin/src/routes/administrationRoutes.ts
  src/explore-education-statistics-admin/src/services/methodologyService.ts
Labels: SOW4

#2622 SOW4 Bug fixes
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyUpdateRequest.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyMethodologyViewModel.cs
Labels: SOW4

#2626 EES-2458 Remove unused BAU methodologies page
  src/explore-education-statistics-admin/src/contexts/AuthContext.tsx
  src/explore-education-statistics-admin/src/services/permissionService.ts
Labels: SOW4

#2627 EES-2473 Add missing dependencies to Publisher
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs
Labels: SOW4

#2618 Ees 2222 UI tests for sow4 create methodology flow 2
  src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210601153005_EES2195AddPublicationMethodology.cs
  tests/robot-tests/.env.example
  tests/robot-tests/listeners/KeywordListener.py
  tests/robot-tests/run_tests.py
  tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
  tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
  tests/robot-tests/tests/admin/bau/create_methodology_for_publication.robot
  tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
  tests/robot-tests/tests/admin/bau/delete_subject.robot
  tests/robot-tests/tests/admin/bau/legacy_releases.robot
  tests/robot-tests/tests/admin/bau/link_publication_to_external_methodology.robot
  tests/robot-tests/tests/admin/bau/prerelease.robot
  tests/robot-tests/tests/admin/bau/release_status.robot
  tests/robot-tests/tests/admin/bau/upload_files.robot
  tests/robot-tests/tests/admin_and_public/bau/footnotes.robot
  tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
  tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
  tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
  tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
  tests/robot-tests/tests/admin_and_public/bau/release_and_publication_role_permissions.robot
  tests/robot-tests/tests/general_public/download_page.robot
  tests/robot-tests/tests/general_public/methodologies_page.robot
  tests/robot-tests/tests/general_public/methodology_page_absence.robot
  tests/robot-tests/tests/general_public/miscellaneous.robot
  tests/robot-tests/tests/general_public/notifications_absence.robot
  tests/robot-tests/tests/general_public/release_page_absence.robot
  tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
  tests/robot-tests/tests/libs/admin-common.robot
  tests/robot-tests/tests/libs/charts.robot
  tests/robot-tests/tests/libs/common.robot
  tests/robot-tests/tests/libs/public-utilities.py
  tests/robot-tests/tests/libs/tables.robot
  tests/robot-tests/tests/libs/utilities.py
Labels: SOW4

#2637 EES-2423 Remove reference to InternalReleaseNote on SOW4 branch
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
Labels: SOW4

#2634 EES-2466 Set Methodology Published dates when they first turn publicly accessible
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
  src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs
Labels: SOW4
