Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2022-09, with the labels that each got.

#3492 Bugfix/EES-3648 Fix deserialisation error occurring when retrieving publications from blob cache
  src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/MethodologyCacheServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/ThemeCacheServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/ContactViewModel.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/ExternalMethodologyViewModel.cs
Labels: bug

#3498 Bugfix/EES-3648 Fix deserialisation error occurring when retrieving publications from blob cache
  src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/LegacyReleaseViewModel.cs
Labels: bug

#3510 upgrading python dependencies
  Pipfile
  Pipfile.lock
Labels: do not merge

#3525 Public snapshot changes
  tests/robot-tests/tests/snapshots/find_stats_snapshot.json
Labels: snapshots
