Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2022-10, with the labels that each got.

#3535 EES-3751 🐛 Configure PermalinkMigrationService to use publisher's storage account
  src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
Labels: bug

#3538 Public snapshot changes
  tests/robot-tests/tests/snapshots/all_methodologies_snapshot.json
  tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
  tests/robot-tests/tests/snapshots/find_stats_snapshot.json
  tests/robot-tests/tests/snapshots/table_tool_snapshot.json
Labels: snapshots

#3544 EES-3747 Increase statistics database size in Prod from 450Gb to 550Gb
  infrastructure/parameters/prod.parameters.json
Labels: hotfix

#3554 EES-3732 Fix clean-up performance test
  tests/performance-tests/package.json
  tests/performance-tests/src/tests/maintenance/cleanUp.test.ts
  tests/performance-tests/src/tests/public/getReleaseApi.test.ts
Labels: testing

#3562 EES-3813 - replace print() statements with logger
  tests/robot-tests/listeners/KeywordListener.py
  tests/robot-tests/run_tests.py
  tests/robot-tests/scripts/run_tests_pipeline.py
  tests/robot-tests/scripts/visual-testing/compare_images.py
  tests/robot-tests/tests/libs/create_emulator_release_files.py
  tests/robot-tests/tests/libs/logger.py
  tests/robot-tests/tests/libs/setup_auth_variables.py
  tests/robot-tests/tests/libs/slack.py
Labels: do not merge

#3587 EES-3845 Increase statistics database size in Prod from 550Gb to 650Gb
  infrastructure/parameters/prod.parameters.json
Labels: hotfix
