Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2022-12, with the labels that each got.

#3667 EES-3923 - upgrade recharts to latest
  src/explore-education-statistics-admin/package-lock.json
  src/explore-education-statistics-admin/package.json
  src/explore-education-statistics-common/package-lock.json
  src/explore-education-statistics-common/package.json
  src/explore-education-statistics-common/src/modules/charts/components/ChartContainer.tsx
  src/explore-education-statistics-common/src/modules/charts/components/CustomReferenceLineLabel.tsx
  src/explore-education-statistics-common/src/modules/charts/components/CustomTooltip.tsx
  src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx
  src/explore-education-statistics-common/src/modules/charts/components/LineChartLabel.tsx
  src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx
  src/explore-education-statistics-common/src/modules/charts/components/hooks/useLegend.ts
  src/explore-education-statistics-common/src/modules/charts/components/utils/createReferenceLine.tsx
  src/explore-education-statistics-common/src/modules/charts/components/utils/getReferenceLineLabelPosition.ts
  src/explore-education-statistics-common/src/modules/charts/util/domainTicks.ts
  src/explore-education-statistics-common/src/styles/_recharts.scss
  src/explore-education-statistics-common/src/types/recharts.d.ts
  src/explore-education-statistics-common/test/setupGlobals.js
  src/explore-education-statistics-frontend/package-lock.json
  src/explore-education-statistics-frontend/package.json
  src/explore-education-statistics-frontend/src/components/FluidChartContainer.tsx
Labels: do not merge

#3706 Bump Newtonsoft.Json from 12.0.3 to 13.0.2
  src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj
  src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
  src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj
Labels: dependencies

#3715 EES-3958 Add missing grant on EmbedBlocks table related to EES-3682
  src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221214184932_EES3958_GrantEmbedBlockToContentUser.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221214184932_EES3958_GrantEmbedBlockToContentUser.cs
Labels: bug

#3716 EES-3959 Adding a temporary time identifier added to give the correct order to a release of the National Tutoring Pprogramme publication
  src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs
  src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifierCategory.cs
Labels: do not merge
