Repository dfe-analytical-services/explore-education-statistics, pull requests merged in 2025-06, with the labels that each got.

#5971 chore(tests): Update test snapshots 05-06-2025
  tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
  tests/robot-tests/tests/snapshots/find_statistics_snapshot.json
  tests/robot-tests/tests/snapshots/table_tool_snapshot.json
Labels: snapshots, automated

#5976 EES-6126 - (STEP 3) Rename the existing publication role `Approver` to `Allower`
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Security/SignInControllerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/AssignPrereleaseContactsToSpecificReleaseAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MarkMethodologyAsApprovedAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MarkMethodologyAsDraftAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MarkMethodologyAsHigherReviewAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ReleaseStatusAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificMethodologyAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificReleaseVersionAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewReleaseStatusHistoryAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificMethodologyAuthorizationHandlerTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificPreReleaseSummaryAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificPublicationReleaseTeamAccessAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificReleaseAuthorizationHandlersTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyApprovalServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationRepositoryTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseApprovalServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseVersionServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserPublicationInviteRepositoryTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserRoleServiceTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250603105107_EES6126-MigratePublicationApproverRoleToAllower.Designer.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250603105107_EES6126-MigratePublicationApproverRoleToAllower.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/AssignPrereleaseContactsToSpecificReleaseAuthorizationHandlers.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MarkMethodologyAsApprovedAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MarkMethodologyAsDraftAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MarkMethodologyAsHigherLevelReviewAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ReleaseStatusAuthorizationHandlers.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/UpdateSpecificMethodologyAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/UpdateSpecificReleaseVersionAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewReleaseStatusHistoryAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewSpecificMethodologyAuthorizationHandlers.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewSpecificPreReleaseSummaryAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewSpecificPublicationReleaseTeamAccessAuthorizationHandler.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/EmailTemplateService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyApprovalService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationRepository.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseApprovalService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseVersionService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserRoleService.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Model/PublicationRole.cs
  src/explore-education-statistics-admin/src/pages/publication/PublicationTeamAccessPage.tsx
  src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationTeamAccessPage.test.tsx
  src/explore-education-statistics-admin/src/pages/users/InvitedUsersPage.tsx
  src/explore-education-statistics-admin/src/pages/users/UserInvitePage.tsx
  src/explore-education-statistics-admin/src/pages/users/__data__/testUserData.ts
  src/explore-education-statistics-admin/src/pages/users/__tests__/UserInvitePage.test.tsx
  src/explore-education-statistics-admin/src/pages/users/components/InviteUserPublicationRoleForm.tsx
  src/explore-education-statistics-admin/src/pages/users/components/PublicationAccessForm.tsx
  src/explore-education-statistics-admin/src/pages/users/components/__tests__/PublicationAccessForm.test.tsx
  src/explore-education-statistics-admin/src/services/types/PublicationRole.ts
  src/explore-education-statistics-admin/src/services/userService.ts
  src/explore-education-statistics-admin/src/utils/publicationRoleDisplayName.ts
  tests/robot-tests/tests/admin/analyst/edit_and_approve_release_as_publication_approver.robot
Labels: do not merge

#6031 chore(tests): Update test snapshots 13-06-2025
  tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
  tests/robot-tests/tests/snapshots/find_statistics_snapshot.json
  tests/robot-tests/tests/snapshots/table_tool_snapshot.json
Labels: snapshots, automated

#6038 EES-5898 Move data set files before triggering import
  src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetFileStorage.cs
Labels: hotfix

#6081 EES-6285 Base64 encode `releaseSlug` for safe use in HTTP headers
  infrastructure/templates/search/scripts/SetupSearchService.ps1
  src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Extensions/ReleaseSearchableDocumentExtensionsTests.cs
  src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ReleaseSearchableDocumentExtensions.cs
Labels: hotfix
